version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: .docker/app_test/Dockerfile
    restart: always
    depends_on:
      - db
  db:
    image: mysql:8.0-oracle
    restart: always
    volumes:
      - db-test-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dv
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  db-test-data: