version: "3.7"
services:
    app:
        build:
            context: .docker/app
            args:
                UID: ${UID}
                GID: ${GID}
        environment:
            PHP_IDE_CONFIG: serverName=api
        restart: always
        depends_on:
            - db
            - redis
        volumes:
            - ./:/var/www/html
        command: dockerize -wait tcp://db:3306 -- bash -c "php-fpm"
        networks:
            - default

    db:
        image: percona/percona-server:latest
        platform: linux/amd64
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 13306:3306

    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www/html
            - .docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - .docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        ports:
            - '${APP_PORT:-80}:80'

    redis:
        image: redis:alpine
        volumes:
            - redis-data:/data
        ports:
            - 16379:6379

    swagger:
        image: swaggerapi/swagger-ui
        volumes:
            - ./storage/api-docs:/app
        environment:
            SWAGGER_JSON: /app/swagger.json
        ports:
            - 8005:8080

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - default

networks:
    default:
        name: dv_backend_network
        driver: bridge
        external: true

volumes:
    db-data:
    redis-data:
